=== codylin/Lab7Take2/Schedule.dtd
<!ELEMENT schedule (course_perspective, period_perspective, day_perspective)+>

<!-- Course Perspective -->

<!ELEMENT course_perspective (course_view)+>
<!ELEMENT course_view (dayOfWeek, period, room, instructor)+>
<!ATTLIST course_view course_num (4620|4650|4660|4770|4850|4910) #REQUIRED>

<!-- Period Perspective -->
<!ELEMENT period_perspective (period_view)+>
<!ELEMENT period_view (course, dayOfWeek, room, instructor)+>
<!ATTLIST period_view time (830|930|1030|1130|1230|1330|1430|1530|1630) #REQUIRED>

<!-- DayOfWeek Perspective -->
<!ELEMENT day_perspective (day_view)+>
<!ELEMENT day_view (period, course, room, instructor)+>
<!ATTLIST day_view day (1|2|3|4|5) #REQUIRED>

<!-- ELEMENTS -->
<!ELEMENT course (#PCDATA)>

<!ELEMENT dayOfWeek (#PCDATA)>
<!ATTLIST dayOfWeek day (1|2|3|4|5) #REQUIRED>
	
<!ELEMENT period (#PCDATA)>
<!ATTLIST period
	time (830|930|1030|1130|1230|1330|1430|1530|1630)
	#REQUIRED >
		
<!ELEMENT room (#PCDATA)>

<!ELEMENT instructor (#PCDATA)>

=== codylin/Lab7Take2/period.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE period_perspective SYSTEM "Schedule.dtd">

<period_perspective>
    <period_view time="1130">
        <dayOfWeek day="1"></dayOfWeek>
        <course>ACIT4650Lab</course>
        <instructor>Dargahi, Farnaz</instructor>
        <room>SE12-306</room>
	
        <dayOfWeek day="4"></dayOfWeek>
        <course>ACIT4910Lab</course>
        <instructor>Richard Chau</instructor>
        <room>SE12-306</room>
                
        <dayOfWeek day="5"></dayOfWeek>
        <course>ACIT4770T</course>
        <instructor>Trevor Lord</instructor>
        <room>SE12-306</room>
    </period_view>
</period_perspective>

=== codylin/Lab7Take2/course.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE course_perspective SYSTEM "Schedule.dtd">

<course_perspective>
    <course_view course_num="4650">
    <dayOfWeek day="1">Monday</dayOfWeek>
    <period time="1030"></period>
    <room>SE12 306</room>
    <instructor>Medhat Elmasry</instructor>
    <dayOfWeek day="1">Monday</dayOfWeek>
    <period time="1130"></period>
    <room>SE12 306</room>
    <instructor>Medhat Elmasry</instructor>
    <dayOfWeek day="1">Monday</dayOfWeek>
    <period time="1630"></period>
    <room>SE6 205</room>
    <instructor>Medhat Elmasry</instructor>
    </course_view>
</course_perspective>
